diff a/drivers/misc/Makefile b/drivers/misc/Makefile	(rejected hunks)
@@ -77,3 +77,5 @@ obj-$(CONFIG_LGE_MODEM_WATCHER)	+= modem_watcher.o
 obj-$(CONFIG_TS0710_MUX)	+= ts0710mux/
 
 obj-$(CONFIG_FSYNC_CONTROL)	+= fsync_control.o
+obj-$(CONFIG_CUSTOM_VOLTAGE)	+= custom_voltage.o
+
