diff a/drivers/misc/Makefile b/drivers/misc/Makefile	(rejected hunks)
@@ -78,3 +78,4 @@ obj-$(CONFIG_TS0710_MUX)	+= ts0710mux/
 
 obj-$(CONFIG_FSYNC_CONTROL)	+= fsync_control.o
 obj-$(CONFIG_CUSTOM_VOLTAGE)	+= custom_voltage.o
+obj-$(CONFIG_SOUND_CONTROL)	+= sound_control.o
